edition: 1.0.0
name: coupons-app
access: "default"

vars: # 全局变量
  region: "cn-hangzhou"
  image_namespace: "fa"
  image_name: "coupons:v1.0"
  service:
    name: "couponsService"

services:
  couponsService:
    component: fc
    actions:
      pre-deploy:
        - component: fc build --use-docker --dockerfile ./Dockerfile
    props:
      region: ${vars.region}
      service: ${vars.service}
      function:
        name: "couponsFc"
        runtime: custom-container
        timeout: 60
        memorySize: 512
        instanceConcurrency: 100
        caPort: 80
        customContainerConfig:
          image: "registry.${vars.region}.aliyuncs.com/${vars.image_namespace}/${vars.image_name}"
      triggers:
        - name: httpTrigger
          type: http
          config:
            authType: anonymous
            methods:
              - GET
              - POST
              - PUT
              - DELETE
              - HEAD
              - OPTIONS
      customDomains:
        - domainName: Auto
          protocol: HTTP
          routeConfigs:
            - path: /*
              